# Generated by Django 2.2.2 on 2019-10-02 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20191002_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 12, 7, 51, 874156)),
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 12, 7, 51, 875153)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 12, 7, 51, 875153)),
        ),
    ]
